#!/bin/bash

# you may need to modify this for your system


dockerargs="--rm --platform linux/amd64 -it -e DISPLAY=host.docker.internal:0 -v `pwd`:/config"
if [ $# -eq 1 ]; then
    dockerfile=$1
else
    dockerfile="phwl/elec3608-cad:latest" # the default docker file
fi

echo "docker run $dockerargs $dockerfile"
docker run $dockerargs $dockerfile

